// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldLastOrgID holds the string denoting the last_org_id field in the database.
	FieldLastOrgID = "last_org_id"
	// FieldLastProjectID holds the string denoting the last_project_id field in the database.
	FieldLastProjectID = "last_project_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeOrganizations holds the string denoting the organizations edge name in mutations.
	EdgeOrganizations = "organizations"
	// EdgeProjects holds the string denoting the projects edge name in mutations.
	EdgeProjects = "projects"
	// EdgeSentInvites holds the string denoting the sent_invites edge name in mutations.
	EdgeSentInvites = "sent_invites"
	// EdgeLastOrganization holds the string denoting the last_organization edge name in mutations.
	EdgeLastOrganization = "last_organization"
	// EdgeLastProject holds the string denoting the last_project edge name in mutations.
	EdgeLastProject = "last_project"
	// EdgeOrganizationMemberships holds the string denoting the organization_memberships edge name in mutations.
	EdgeOrganizationMemberships = "organization_memberships"
	// EdgeProjectMemberships holds the string denoting the project_memberships edge name in mutations.
	EdgeProjectMemberships = "project_memberships"
	// Table holds the table name of the user in the database.
	Table = "users"
	// OrganizationsTable is the table that holds the organizations relation/edge. The primary key declared below.
	OrganizationsTable = "organization_members"
	// OrganizationsInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationsInverseTable = "organizations"
	// ProjectsTable is the table that holds the projects relation/edge. The primary key declared below.
	ProjectsTable = "project_members"
	// ProjectsInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectsInverseTable = "projects"
	// SentInvitesTable is the table that holds the sent_invites relation/edge.
	SentInvitesTable = "invites"
	// SentInvitesInverseTable is the table name for the Invite entity.
	// It exists in this package in order to avoid circular dependency with the "invite" package.
	SentInvitesInverseTable = "invites"
	// SentInvitesColumn is the table column denoting the sent_invites relation/edge.
	SentInvitesColumn = "invited_by_id"
	// LastOrganizationTable is the table that holds the last_organization relation/edge.
	LastOrganizationTable = "users"
	// LastOrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	LastOrganizationInverseTable = "organizations"
	// LastOrganizationColumn is the table column denoting the last_organization relation/edge.
	LastOrganizationColumn = "last_org_id"
	// LastProjectTable is the table that holds the last_project relation/edge.
	LastProjectTable = "users"
	// LastProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	LastProjectInverseTable = "projects"
	// LastProjectColumn is the table column denoting the last_project relation/edge.
	LastProjectColumn = "last_project_id"
	// OrganizationMembershipsTable is the table that holds the organization_memberships relation/edge.
	OrganizationMembershipsTable = "organization_members"
	// OrganizationMembershipsInverseTable is the table name for the OrganizationMember entity.
	// It exists in this package in order to avoid circular dependency with the "organizationmember" package.
	OrganizationMembershipsInverseTable = "organization_members"
	// OrganizationMembershipsColumn is the table column denoting the organization_memberships relation/edge.
	OrganizationMembershipsColumn = "user_id"
	// ProjectMembershipsTable is the table that holds the project_memberships relation/edge.
	ProjectMembershipsTable = "project_members"
	// ProjectMembershipsInverseTable is the table name for the ProjectMember entity.
	// It exists in this package in order to avoid circular dependency with the "projectmember" package.
	ProjectMembershipsInverseTable = "project_members"
	// ProjectMembershipsColumn is the table column denoting the project_memberships relation/edge.
	ProjectMembershipsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPasswordHash,
	FieldDisplayName,
	FieldLastOrgID,
	FieldLastProjectID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// OrganizationsPrimaryKey and OrganizationsColumn2 are the table columns denoting the
	// primary key for the organizations relation (M2M).
	OrganizationsPrimaryKey = []string{"user_id", "organization_id"}
	// ProjectsPrimaryKey and ProjectsColumn2 are the table columns denoting the
	// primary key for the projects relation (M2M).
	ProjectsPrimaryKey = []string{"user_id", "project_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DisplayNameValidator is a validator for the "display_name" field. It is called by the builders before save.
	DisplayNameValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByLastOrgID orders the results by the last_org_id field.
func ByLastOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastOrgID, opts...).ToFunc()
}

// ByLastProjectID orders the results by the last_project_id field.
func ByLastProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProjectID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrganizationsCount orders the results by organizations count.
func ByOrganizationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrganizationsStep(), opts...)
	}
}

// ByOrganizations orders the results by organizations terms.
func ByOrganizations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectsCount orders the results by projects count.
func ByProjectsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectsStep(), opts...)
	}
}

// ByProjects orders the results by projects terms.
func ByProjects(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySentInvitesCount orders the results by sent_invites count.
func BySentInvitesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSentInvitesStep(), opts...)
	}
}

// BySentInvites orders the results by sent_invites terms.
func BySentInvites(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSentInvitesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLastOrganizationField orders the results by last_organization field.
func ByLastOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLastOrganizationStep(), sql.OrderByField(field, opts...))
	}
}

// ByLastProjectField orders the results by last_project field.
func ByLastProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLastProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByOrganizationMembershipsCount orders the results by organization_memberships count.
func ByOrganizationMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOrganizationMembershipsStep(), opts...)
	}
}

// ByOrganizationMemberships orders the results by organization_memberships terms.
func ByOrganizationMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectMembershipsCount orders the results by project_memberships count.
func ByProjectMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectMembershipsStep(), opts...)
	}
}

// ByProjectMemberships orders the results by project_memberships terms.
func ByProjectMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrganizationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, OrganizationsTable, OrganizationsPrimaryKey...),
	)
}
func newProjectsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, ProjectsTable, ProjectsPrimaryKey...),
	)
}
func newSentInvitesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SentInvitesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SentInvitesTable, SentInvitesColumn),
	)
}
func newLastOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LastOrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LastOrganizationTable, LastOrganizationColumn),
	)
}
func newLastProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LastProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, LastProjectTable, LastProjectColumn),
	)
}
func newOrganizationMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationMembershipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, OrganizationMembershipsTable, OrganizationMembershipsColumn),
	)
}
func newProjectMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectMembershipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ProjectMembershipsTable, ProjectMembershipsColumn),
	)
}
