// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Invite is the predicate function for invite builders.
type Invite func(*sql.Selector)

// Organization is the predicate function for organization builders.
type Organization func(*sql.Selector)

// OrganizationMember is the predicate function for organizationmember builders.
type OrganizationMember func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectMember is the predicate function for projectmember builders.
type ProjectMember func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
