// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/invite"
	"backend/ent/organization"
	"backend/ent/project"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Invite is the model entity for the Invite schema.
type Invite struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID uuid.UUID `json:"organization_id,omitempty"`
	// ProjectID holds the value of the "project_id" field.
	ProjectID *uuid.UUID `json:"project_id,omitempty"`
	// Role holds the value of the "role" field.
	Role invite.Role `json:"role,omitempty"`
	// ProjectPermission holds the value of the "project_permission" field.
	ProjectPermission *invite.ProjectPermission `json:"project_permission,omitempty"`
	// InvitedByID holds the value of the "invited_by_id" field.
	InvitedByID uuid.UUID `json:"invited_by_id,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the InviteQuery when eager-loading is set.
	Edges        InviteEdges `json:"edges"`
	selectValues sql.SelectValues
}

// InviteEdges holds the relations/edges for other nodes in the graph.
type InviteEdges struct {
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// InvitedBy holds the value of the invited_by edge.
	InvitedBy *User `json:"invited_by,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// InvitedByOrErr returns the InvitedBy value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e InviteEdges) InvitedByOrErr() (*User, error) {
	if e.InvitedBy != nil {
		return e.InvitedBy, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "invited_by"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Invite) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case invite.FieldProjectID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case invite.FieldToken, invite.FieldEmail, invite.FieldRole, invite.FieldProjectPermission:
			values[i] = new(sql.NullString)
		case invite.FieldExpiresAt, invite.FieldUsedAt, invite.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case invite.FieldID, invite.FieldOrganizationID, invite.FieldInvitedByID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Invite fields.
func (i *Invite) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case invite.FieldID:
			if value, ok := values[j].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[j])
			} else if value != nil {
				i.ID = *value
			}
		case invite.FieldToken:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[j])
			} else if value.Valid {
				i.Token = value.String
			}
		case invite.FieldEmail:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[j])
			} else if value.Valid {
				i.Email = value.String
			}
		case invite.FieldOrganizationID:
			if value, ok := values[j].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[j])
			} else if value != nil {
				i.OrganizationID = *value
			}
		case invite.FieldProjectID:
			if value, ok := values[j].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field project_id", values[j])
			} else if value.Valid {
				i.ProjectID = new(uuid.UUID)
				*i.ProjectID = *value.S.(*uuid.UUID)
			}
		case invite.FieldRole:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[j])
			} else if value.Valid {
				i.Role = invite.Role(value.String)
			}
		case invite.FieldProjectPermission:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_permission", values[j])
			} else if value.Valid {
				i.ProjectPermission = new(invite.ProjectPermission)
				*i.ProjectPermission = invite.ProjectPermission(value.String)
			}
		case invite.FieldInvitedByID:
			if value, ok := values[j].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field invited_by_id", values[j])
			} else if value != nil {
				i.InvitedByID = *value
			}
		case invite.FieldExpiresAt:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[j])
			} else if value.Valid {
				i.ExpiresAt = value.Time
			}
		case invite.FieldUsedAt:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[j])
			} else if value.Valid {
				i.UsedAt = new(time.Time)
				*i.UsedAt = value.Time
			}
		case invite.FieldCreatedAt:
			if value, ok := values[j].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[j])
			} else if value.Valid {
				i.CreatedAt = value.Time
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Invite.
// This includes values selected through modifiers, order, etc.
func (i *Invite) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// QueryOrganization queries the "organization" edge of the Invite entity.
func (i *Invite) QueryOrganization() *OrganizationQuery {
	return NewInviteClient(i.config).QueryOrganization(i)
}

// QueryProject queries the "project" edge of the Invite entity.
func (i *Invite) QueryProject() *ProjectQuery {
	return NewInviteClient(i.config).QueryProject(i)
}

// QueryInvitedBy queries the "invited_by" edge of the Invite entity.
func (i *Invite) QueryInvitedBy() *UserQuery {
	return NewInviteClient(i.config).QueryInvitedBy(i)
}

// Update returns a builder for updating this Invite.
// Note that you need to call Invite.Unwrap() before calling this method if this Invite
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Invite) Update() *InviteUpdateOne {
	return NewInviteClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Invite entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Invite) Unwrap() *Invite {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Invite is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Invite) String() string {
	var builder strings.Builder
	builder.WriteString("Invite(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("token=")
	builder.WriteString(i.Token)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(i.Email)
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", i.OrganizationID))
	builder.WriteString(", ")
	if v := i.ProjectID; v != nil {
		builder.WriteString("project_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", i.Role))
	builder.WriteString(", ")
	if v := i.ProjectPermission; v != nil {
		builder.WriteString("project_permission=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("invited_by_id=")
	builder.WriteString(fmt.Sprintf("%v", i.InvitedByID))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(i.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := i.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(i.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Invites is a parsable slice of Invite.
type Invites []*Invite
