// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/invite"
	"backend/ent/organization"
	"backend/ent/predicate"
	"backend/ent/project"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// InviteUpdate is the builder for updating Invite entities.
type InviteUpdate struct {
	config
	hooks    []Hook
	mutation *InviteMutation
}

// Where appends a list predicates to the InviteUpdate builder.
func (iu *InviteUpdate) Where(ps ...predicate.Invite) *InviteUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetToken sets the "token" field.
func (iu *InviteUpdate) SetToken(s string) *InviteUpdate {
	iu.mutation.SetToken(s)
	return iu
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableToken(s *string) *InviteUpdate {
	if s != nil {
		iu.SetToken(*s)
	}
	return iu
}

// SetEmail sets the "email" field.
func (iu *InviteUpdate) SetEmail(s string) *InviteUpdate {
	iu.mutation.SetEmail(s)
	return iu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableEmail(s *string) *InviteUpdate {
	if s != nil {
		iu.SetEmail(*s)
	}
	return iu
}

// SetOrganizationID sets the "organization_id" field.
func (iu *InviteUpdate) SetOrganizationID(u uuid.UUID) *InviteUpdate {
	iu.mutation.SetOrganizationID(u)
	return iu
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableOrganizationID(u *uuid.UUID) *InviteUpdate {
	if u != nil {
		iu.SetOrganizationID(*u)
	}
	return iu
}

// SetProjectID sets the "project_id" field.
func (iu *InviteUpdate) SetProjectID(u uuid.UUID) *InviteUpdate {
	iu.mutation.SetProjectID(u)
	return iu
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableProjectID(u *uuid.UUID) *InviteUpdate {
	if u != nil {
		iu.SetProjectID(*u)
	}
	return iu
}

// ClearProjectID clears the value of the "project_id" field.
func (iu *InviteUpdate) ClearProjectID() *InviteUpdate {
	iu.mutation.ClearProjectID()
	return iu
}

// SetRole sets the "role" field.
func (iu *InviteUpdate) SetRole(i invite.Role) *InviteUpdate {
	iu.mutation.SetRole(i)
	return iu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableRole(i *invite.Role) *InviteUpdate {
	if i != nil {
		iu.SetRole(*i)
	}
	return iu
}

// SetProjectPermission sets the "project_permission" field.
func (iu *InviteUpdate) SetProjectPermission(ip invite.ProjectPermission) *InviteUpdate {
	iu.mutation.SetProjectPermission(ip)
	return iu
}

// SetNillableProjectPermission sets the "project_permission" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableProjectPermission(ip *invite.ProjectPermission) *InviteUpdate {
	if ip != nil {
		iu.SetProjectPermission(*ip)
	}
	return iu
}

// ClearProjectPermission clears the value of the "project_permission" field.
func (iu *InviteUpdate) ClearProjectPermission() *InviteUpdate {
	iu.mutation.ClearProjectPermission()
	return iu
}

// SetInvitedByID sets the "invited_by_id" field.
func (iu *InviteUpdate) SetInvitedByID(u uuid.UUID) *InviteUpdate {
	iu.mutation.SetInvitedByID(u)
	return iu
}

// SetNillableInvitedByID sets the "invited_by_id" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableInvitedByID(u *uuid.UUID) *InviteUpdate {
	if u != nil {
		iu.SetInvitedByID(*u)
	}
	return iu
}

// SetExpiresAt sets the "expires_at" field.
func (iu *InviteUpdate) SetExpiresAt(t time.Time) *InviteUpdate {
	iu.mutation.SetExpiresAt(t)
	return iu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableExpiresAt(t *time.Time) *InviteUpdate {
	if t != nil {
		iu.SetExpiresAt(*t)
	}
	return iu
}

// SetUsedAt sets the "used_at" field.
func (iu *InviteUpdate) SetUsedAt(t time.Time) *InviteUpdate {
	iu.mutation.SetUsedAt(t)
	return iu
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableUsedAt(t *time.Time) *InviteUpdate {
	if t != nil {
		iu.SetUsedAt(*t)
	}
	return iu
}

// ClearUsedAt clears the value of the "used_at" field.
func (iu *InviteUpdate) ClearUsedAt() *InviteUpdate {
	iu.mutation.ClearUsedAt()
	return iu
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (iu *InviteUpdate) SetOrganization(o *Organization) *InviteUpdate {
	return iu.SetOrganizationID(o.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (iu *InviteUpdate) SetProject(p *Project) *InviteUpdate {
	return iu.SetProjectID(p.ID)
}

// SetInvitedBy sets the "invited_by" edge to the User entity.
func (iu *InviteUpdate) SetInvitedBy(u *User) *InviteUpdate {
	return iu.SetInvitedByID(u.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (iu *InviteUpdate) Mutation() *InviteMutation {
	return iu.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (iu *InviteUpdate) ClearOrganization() *InviteUpdate {
	iu.mutation.ClearOrganization()
	return iu
}

// ClearProject clears the "project" edge to the Project entity.
func (iu *InviteUpdate) ClearProject() *InviteUpdate {
	iu.mutation.ClearProject()
	return iu
}

// ClearInvitedBy clears the "invited_by" edge to the User entity.
func (iu *InviteUpdate) ClearInvitedBy() *InviteUpdate {
	iu.mutation.ClearInvitedBy()
	return iu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *InviteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *InviteUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *InviteUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *InviteUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *InviteUpdate) check() error {
	if v, ok := iu.mutation.Token(); ok {
		if err := invite.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Invite.token": %w`, err)}
		}
	}
	if v, ok := iu.mutation.Email(); ok {
		if err := invite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Invite.email": %w`, err)}
		}
	}
	if v, ok := iu.mutation.Role(); ok {
		if err := invite.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Invite.role": %w`, err)}
		}
	}
	if v, ok := iu.mutation.ProjectPermission(); ok {
		if err := invite.ProjectPermissionValidator(v); err != nil {
			return &ValidationError{Name: "project_permission", err: fmt.Errorf(`ent: validator failed for field "Invite.project_permission": %w`, err)}
		}
	}
	if iu.mutation.OrganizationCleared() && len(iu.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.organization"`)
	}
	if iu.mutation.InvitedByCleared() && len(iu.mutation.InvitedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.invited_by"`)
	}
	return nil
}

func (iu *InviteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Token(); ok {
		_spec.SetField(invite.FieldToken, field.TypeString, value)
	}
	if value, ok := iu.mutation.Email(); ok {
		_spec.SetField(invite.FieldEmail, field.TypeString, value)
	}
	if value, ok := iu.mutation.Role(); ok {
		_spec.SetField(invite.FieldRole, field.TypeEnum, value)
	}
	if value, ok := iu.mutation.ProjectPermission(); ok {
		_spec.SetField(invite.FieldProjectPermission, field.TypeEnum, value)
	}
	if iu.mutation.ProjectPermissionCleared() {
		_spec.ClearField(invite.FieldProjectPermission, field.TypeEnum)
	}
	if value, ok := iu.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.UsedAt(); ok {
		_spec.SetField(invite.FieldUsedAt, field.TypeTime, value)
	}
	if iu.mutation.UsedAtCleared() {
		_spec.ClearField(invite.FieldUsedAt, field.TypeTime)
	}
	if iu.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.OrganizationTable,
			Columns: []string{invite.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.OrganizationTable,
			Columns: []string{invite.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iu.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.ProjectTable,
			Columns: []string{invite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.ProjectTable,
			Columns: []string{invite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iu.mutation.InvitedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InvitedByTable,
			Columns: []string{invite.InvitedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.InvitedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InvitedByTable,
			Columns: []string{invite.InvitedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// InviteUpdateOne is the builder for updating a single Invite entity.
type InviteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InviteMutation
}

// SetToken sets the "token" field.
func (iuo *InviteUpdateOne) SetToken(s string) *InviteUpdateOne {
	iuo.mutation.SetToken(s)
	return iuo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableToken(s *string) *InviteUpdateOne {
	if s != nil {
		iuo.SetToken(*s)
	}
	return iuo
}

// SetEmail sets the "email" field.
func (iuo *InviteUpdateOne) SetEmail(s string) *InviteUpdateOne {
	iuo.mutation.SetEmail(s)
	return iuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableEmail(s *string) *InviteUpdateOne {
	if s != nil {
		iuo.SetEmail(*s)
	}
	return iuo
}

// SetOrganizationID sets the "organization_id" field.
func (iuo *InviteUpdateOne) SetOrganizationID(u uuid.UUID) *InviteUpdateOne {
	iuo.mutation.SetOrganizationID(u)
	return iuo
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableOrganizationID(u *uuid.UUID) *InviteUpdateOne {
	if u != nil {
		iuo.SetOrganizationID(*u)
	}
	return iuo
}

// SetProjectID sets the "project_id" field.
func (iuo *InviteUpdateOne) SetProjectID(u uuid.UUID) *InviteUpdateOne {
	iuo.mutation.SetProjectID(u)
	return iuo
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableProjectID(u *uuid.UUID) *InviteUpdateOne {
	if u != nil {
		iuo.SetProjectID(*u)
	}
	return iuo
}

// ClearProjectID clears the value of the "project_id" field.
func (iuo *InviteUpdateOne) ClearProjectID() *InviteUpdateOne {
	iuo.mutation.ClearProjectID()
	return iuo
}

// SetRole sets the "role" field.
func (iuo *InviteUpdateOne) SetRole(i invite.Role) *InviteUpdateOne {
	iuo.mutation.SetRole(i)
	return iuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableRole(i *invite.Role) *InviteUpdateOne {
	if i != nil {
		iuo.SetRole(*i)
	}
	return iuo
}

// SetProjectPermission sets the "project_permission" field.
func (iuo *InviteUpdateOne) SetProjectPermission(ip invite.ProjectPermission) *InviteUpdateOne {
	iuo.mutation.SetProjectPermission(ip)
	return iuo
}

// SetNillableProjectPermission sets the "project_permission" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableProjectPermission(ip *invite.ProjectPermission) *InviteUpdateOne {
	if ip != nil {
		iuo.SetProjectPermission(*ip)
	}
	return iuo
}

// ClearProjectPermission clears the value of the "project_permission" field.
func (iuo *InviteUpdateOne) ClearProjectPermission() *InviteUpdateOne {
	iuo.mutation.ClearProjectPermission()
	return iuo
}

// SetInvitedByID sets the "invited_by_id" field.
func (iuo *InviteUpdateOne) SetInvitedByID(u uuid.UUID) *InviteUpdateOne {
	iuo.mutation.SetInvitedByID(u)
	return iuo
}

// SetNillableInvitedByID sets the "invited_by_id" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableInvitedByID(u *uuid.UUID) *InviteUpdateOne {
	if u != nil {
		iuo.SetInvitedByID(*u)
	}
	return iuo
}

// SetExpiresAt sets the "expires_at" field.
func (iuo *InviteUpdateOne) SetExpiresAt(t time.Time) *InviteUpdateOne {
	iuo.mutation.SetExpiresAt(t)
	return iuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableExpiresAt(t *time.Time) *InviteUpdateOne {
	if t != nil {
		iuo.SetExpiresAt(*t)
	}
	return iuo
}

// SetUsedAt sets the "used_at" field.
func (iuo *InviteUpdateOne) SetUsedAt(t time.Time) *InviteUpdateOne {
	iuo.mutation.SetUsedAt(t)
	return iuo
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableUsedAt(t *time.Time) *InviteUpdateOne {
	if t != nil {
		iuo.SetUsedAt(*t)
	}
	return iuo
}

// ClearUsedAt clears the value of the "used_at" field.
func (iuo *InviteUpdateOne) ClearUsedAt() *InviteUpdateOne {
	iuo.mutation.ClearUsedAt()
	return iuo
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (iuo *InviteUpdateOne) SetOrganization(o *Organization) *InviteUpdateOne {
	return iuo.SetOrganizationID(o.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (iuo *InviteUpdateOne) SetProject(p *Project) *InviteUpdateOne {
	return iuo.SetProjectID(p.ID)
}

// SetInvitedBy sets the "invited_by" edge to the User entity.
func (iuo *InviteUpdateOne) SetInvitedBy(u *User) *InviteUpdateOne {
	return iuo.SetInvitedByID(u.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (iuo *InviteUpdateOne) Mutation() *InviteMutation {
	return iuo.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (iuo *InviteUpdateOne) ClearOrganization() *InviteUpdateOne {
	iuo.mutation.ClearOrganization()
	return iuo
}

// ClearProject clears the "project" edge to the Project entity.
func (iuo *InviteUpdateOne) ClearProject() *InviteUpdateOne {
	iuo.mutation.ClearProject()
	return iuo
}

// ClearInvitedBy clears the "invited_by" edge to the User entity.
func (iuo *InviteUpdateOne) ClearInvitedBy() *InviteUpdateOne {
	iuo.mutation.ClearInvitedBy()
	return iuo
}

// Where appends a list predicates to the InviteUpdate builder.
func (iuo *InviteUpdateOne) Where(ps ...predicate.Invite) *InviteUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *InviteUpdateOne) Select(field string, fields ...string) *InviteUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Invite entity.
func (iuo *InviteUpdateOne) Save(ctx context.Context) (*Invite, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *InviteUpdateOne) SaveX(ctx context.Context) *Invite {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *InviteUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *InviteUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *InviteUpdateOne) check() error {
	if v, ok := iuo.mutation.Token(); ok {
		if err := invite.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Invite.token": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.Email(); ok {
		if err := invite.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Invite.email": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.Role(); ok {
		if err := invite.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Invite.role": %w`, err)}
		}
	}
	if v, ok := iuo.mutation.ProjectPermission(); ok {
		if err := invite.ProjectPermissionValidator(v); err != nil {
			return &ValidationError{Name: "project_permission", err: fmt.Errorf(`ent: validator failed for field "Invite.project_permission": %w`, err)}
		}
	}
	if iuo.mutation.OrganizationCleared() && len(iuo.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.organization"`)
	}
	if iuo.mutation.InvitedByCleared() && len(iuo.mutation.InvitedByIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.invited_by"`)
	}
	return nil
}

func (iuo *InviteUpdateOne) sqlSave(ctx context.Context) (_node *Invite, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invite.FieldID)
		for _, f := range fields {
			if !invite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Token(); ok {
		_spec.SetField(invite.FieldToken, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Email(); ok {
		_spec.SetField(invite.FieldEmail, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Role(); ok {
		_spec.SetField(invite.FieldRole, field.TypeEnum, value)
	}
	if value, ok := iuo.mutation.ProjectPermission(); ok {
		_spec.SetField(invite.FieldProjectPermission, field.TypeEnum, value)
	}
	if iuo.mutation.ProjectPermissionCleared() {
		_spec.ClearField(invite.FieldProjectPermission, field.TypeEnum)
	}
	if value, ok := iuo.mutation.ExpiresAt(); ok {
		_spec.SetField(invite.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.UsedAt(); ok {
		_spec.SetField(invite.FieldUsedAt, field.TypeTime, value)
	}
	if iuo.mutation.UsedAtCleared() {
		_spec.ClearField(invite.FieldUsedAt, field.TypeTime)
	}
	if iuo.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.OrganizationTable,
			Columns: []string{invite.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.OrganizationTable,
			Columns: []string{invite.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iuo.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.ProjectTable,
			Columns: []string{invite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.ProjectTable,
			Columns: []string{invite.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if iuo.mutation.InvitedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InvitedByTable,
			Columns: []string{invite.InvitedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.InvitedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.InvitedByTable,
			Columns: []string{invite.InvitedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Invite{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
