// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/organization"
	"backend/ent/organizationmember"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// OrganizationMember is the model entity for the OrganizationMember schema.
type OrganizationMember struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID uuid.UUID `json:"organization_id,omitempty"`
	// Role holds the value of the "role" field.
	Role organizationmember.Role `json:"role,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationMemberQuery when eager-loading is set.
	Edges        OrganizationMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationMemberEdges holds the relations/edges for other nodes in the graph.
type OrganizationMemberEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Organization holds the value of the organization edge.
	Organization *Organization `json:"organization,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrganizationMemberEdges) OrganizationOrErr() (*Organization, error) {
	if e.Organization != nil {
		return e.Organization, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationmember.FieldID:
			values[i] = new(sql.NullInt64)
		case organizationmember.FieldRole:
			values[i] = new(sql.NullString)
		case organizationmember.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case organizationmember.FieldUserID, organizationmember.FieldOrganizationID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationMember fields.
func (om *OrganizationMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationmember.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			om.ID = int(value.Int64)
		case organizationmember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				om.UserID = *value
			}
		case organizationmember.FieldOrganizationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value != nil {
				om.OrganizationID = *value
			}
		case organizationmember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				om.Role = organizationmember.Role(value.String)
			}
		case organizationmember.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				om.CreatedAt = value.Time
			}
		default:
			om.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationMember.
// This includes values selected through modifiers, order, etc.
func (om *OrganizationMember) Value(name string) (ent.Value, error) {
	return om.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OrganizationMember entity.
func (om *OrganizationMember) QueryUser() *UserQuery {
	return NewOrganizationMemberClient(om.config).QueryUser(om)
}

// QueryOrganization queries the "organization" edge of the OrganizationMember entity.
func (om *OrganizationMember) QueryOrganization() *OrganizationQuery {
	return NewOrganizationMemberClient(om.config).QueryOrganization(om)
}

// Update returns a builder for updating this OrganizationMember.
// Note that you need to call OrganizationMember.Unwrap() before calling this method if this OrganizationMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (om *OrganizationMember) Update() *OrganizationMemberUpdateOne {
	return NewOrganizationMemberClient(om.config).UpdateOne(om)
}

// Unwrap unwraps the OrganizationMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (om *OrganizationMember) Unwrap() *OrganizationMember {
	_tx, ok := om.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrganizationMember is not a transactional entity")
	}
	om.config.driver = _tx.drv
	return om
}

// String implements the fmt.Stringer.
func (om *OrganizationMember) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", om.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", om.UserID))
	builder.WriteString(", ")
	builder.WriteString("organization_id=")
	builder.WriteString(fmt.Sprintf("%v", om.OrganizationID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(fmt.Sprintf("%v", om.Role))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(om.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationMembers is a parsable slice of OrganizationMember.
type OrganizationMembers []*OrganizationMember
