// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/organization"
	"backend/ent/organizationmember"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationMemberCreate is the builder for creating a OrganizationMember entity.
type OrganizationMemberCreate struct {
	config
	mutation *OrganizationMemberMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (omc *OrganizationMemberCreate) SetUserID(u uuid.UUID) *OrganizationMemberCreate {
	omc.mutation.SetUserID(u)
	return omc
}

// SetOrganizationID sets the "organization_id" field.
func (omc *OrganizationMemberCreate) SetOrganizationID(u uuid.UUID) *OrganizationMemberCreate {
	omc.mutation.SetOrganizationID(u)
	return omc
}

// SetRole sets the "role" field.
func (omc *OrganizationMemberCreate) SetRole(o organizationmember.Role) *OrganizationMemberCreate {
	omc.mutation.SetRole(o)
	return omc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (omc *OrganizationMemberCreate) SetNillableRole(o *organizationmember.Role) *OrganizationMemberCreate {
	if o != nil {
		omc.SetRole(*o)
	}
	return omc
}

// SetCreatedAt sets the "created_at" field.
func (omc *OrganizationMemberCreate) SetCreatedAt(t time.Time) *OrganizationMemberCreate {
	omc.mutation.SetCreatedAt(t)
	return omc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (omc *OrganizationMemberCreate) SetNillableCreatedAt(t *time.Time) *OrganizationMemberCreate {
	if t != nil {
		omc.SetCreatedAt(*t)
	}
	return omc
}

// SetUser sets the "user" edge to the User entity.
func (omc *OrganizationMemberCreate) SetUser(u *User) *OrganizationMemberCreate {
	return omc.SetUserID(u.ID)
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (omc *OrganizationMemberCreate) SetOrganization(o *Organization) *OrganizationMemberCreate {
	return omc.SetOrganizationID(o.ID)
}

// Mutation returns the OrganizationMemberMutation object of the builder.
func (omc *OrganizationMemberCreate) Mutation() *OrganizationMemberMutation {
	return omc.mutation
}

// Save creates the OrganizationMember in the database.
func (omc *OrganizationMemberCreate) Save(ctx context.Context) (*OrganizationMember, error) {
	omc.defaults()
	return withHooks(ctx, omc.sqlSave, omc.mutation, omc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (omc *OrganizationMemberCreate) SaveX(ctx context.Context) *OrganizationMember {
	v, err := omc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (omc *OrganizationMemberCreate) Exec(ctx context.Context) error {
	_, err := omc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omc *OrganizationMemberCreate) ExecX(ctx context.Context) {
	if err := omc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (omc *OrganizationMemberCreate) defaults() {
	if _, ok := omc.mutation.Role(); !ok {
		v := organizationmember.DefaultRole
		omc.mutation.SetRole(v)
	}
	if _, ok := omc.mutation.CreatedAt(); !ok {
		v := organizationmember.DefaultCreatedAt()
		omc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omc *OrganizationMemberCreate) check() error {
	if _, ok := omc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "OrganizationMember.user_id"`)}
	}
	if _, ok := omc.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "OrganizationMember.organization_id"`)}
	}
	if _, ok := omc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "OrganizationMember.role"`)}
	}
	if v, ok := omc.mutation.Role(); ok {
		if err := organizationmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OrganizationMember.role": %w`, err)}
		}
	}
	if _, ok := omc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrganizationMember.created_at"`)}
	}
	if len(omc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "OrganizationMember.user"`)}
	}
	if len(omc.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "OrganizationMember.organization"`)}
	}
	return nil
}

func (omc *OrganizationMemberCreate) sqlSave(ctx context.Context) (*OrganizationMember, error) {
	if err := omc.check(); err != nil {
		return nil, err
	}
	_node, _spec := omc.createSpec()
	if err := sqlgraph.CreateNode(ctx, omc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	omc.mutation.id = &_node.ID
	omc.mutation.done = true
	return _node, nil
}

func (omc *OrganizationMemberCreate) createSpec() (*OrganizationMember, *sqlgraph.CreateSpec) {
	var (
		_node = &OrganizationMember{config: omc.config}
		_spec = sqlgraph.NewCreateSpec(organizationmember.Table, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt))
	)
	if value, ok := omc.mutation.Role(); ok {
		_spec.SetField(organizationmember.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if value, ok := omc.mutation.CreatedAt(); ok {
		_spec.SetField(organizationmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := omc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.UserTable,
			Columns: []string{organizationmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := omc.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.OrganizationTable,
			Columns: []string{organizationmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrganizationMemberCreateBulk is the builder for creating many OrganizationMember entities in bulk.
type OrganizationMemberCreateBulk struct {
	config
	err      error
	builders []*OrganizationMemberCreate
}

// Save creates the OrganizationMember entities in the database.
func (omcb *OrganizationMemberCreateBulk) Save(ctx context.Context) ([]*OrganizationMember, error) {
	if omcb.err != nil {
		return nil, omcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(omcb.builders))
	nodes := make([]*OrganizationMember, len(omcb.builders))
	mutators := make([]Mutator, len(omcb.builders))
	for i := range omcb.builders {
		func(i int, root context.Context) {
			builder := omcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrganizationMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, omcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, omcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, omcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (omcb *OrganizationMemberCreateBulk) SaveX(ctx context.Context) []*OrganizationMember {
	v, err := omcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (omcb *OrganizationMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := omcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omcb *OrganizationMemberCreateBulk) ExecX(ctx context.Context) {
	if err := omcb.Exec(ctx); err != nil {
		panic(err)
	}
}
