// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/organization"
	"backend/ent/organizationmember"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationMemberUpdate is the builder for updating OrganizationMember entities.
type OrganizationMemberUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationMemberMutation
}

// Where appends a list predicates to the OrganizationMemberUpdate builder.
func (omu *OrganizationMemberUpdate) Where(ps ...predicate.OrganizationMember) *OrganizationMemberUpdate {
	omu.mutation.Where(ps...)
	return omu
}

// SetUserID sets the "user_id" field.
func (omu *OrganizationMemberUpdate) SetUserID(u uuid.UUID) *OrganizationMemberUpdate {
	omu.mutation.SetUserID(u)
	return omu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (omu *OrganizationMemberUpdate) SetNillableUserID(u *uuid.UUID) *OrganizationMemberUpdate {
	if u != nil {
		omu.SetUserID(*u)
	}
	return omu
}

// SetOrganizationID sets the "organization_id" field.
func (omu *OrganizationMemberUpdate) SetOrganizationID(u uuid.UUID) *OrganizationMemberUpdate {
	omu.mutation.SetOrganizationID(u)
	return omu
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (omu *OrganizationMemberUpdate) SetNillableOrganizationID(u *uuid.UUID) *OrganizationMemberUpdate {
	if u != nil {
		omu.SetOrganizationID(*u)
	}
	return omu
}

// SetRole sets the "role" field.
func (omu *OrganizationMemberUpdate) SetRole(o organizationmember.Role) *OrganizationMemberUpdate {
	omu.mutation.SetRole(o)
	return omu
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (omu *OrganizationMemberUpdate) SetNillableRole(o *organizationmember.Role) *OrganizationMemberUpdate {
	if o != nil {
		omu.SetRole(*o)
	}
	return omu
}

// SetUser sets the "user" edge to the User entity.
func (omu *OrganizationMemberUpdate) SetUser(u *User) *OrganizationMemberUpdate {
	return omu.SetUserID(u.ID)
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (omu *OrganizationMemberUpdate) SetOrganization(o *Organization) *OrganizationMemberUpdate {
	return omu.SetOrganizationID(o.ID)
}

// Mutation returns the OrganizationMemberMutation object of the builder.
func (omu *OrganizationMemberUpdate) Mutation() *OrganizationMemberMutation {
	return omu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (omu *OrganizationMemberUpdate) ClearUser() *OrganizationMemberUpdate {
	omu.mutation.ClearUser()
	return omu
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (omu *OrganizationMemberUpdate) ClearOrganization() *OrganizationMemberUpdate {
	omu.mutation.ClearOrganization()
	return omu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (omu *OrganizationMemberUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, omu.sqlSave, omu.mutation, omu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (omu *OrganizationMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := omu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (omu *OrganizationMemberUpdate) Exec(ctx context.Context) error {
	_, err := omu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omu *OrganizationMemberUpdate) ExecX(ctx context.Context) {
	if err := omu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omu *OrganizationMemberUpdate) check() error {
	if v, ok := omu.mutation.Role(); ok {
		if err := organizationmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OrganizationMember.role": %w`, err)}
		}
	}
	if omu.mutation.UserCleared() && len(omu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationMember.user"`)
	}
	if omu.mutation.OrganizationCleared() && len(omu.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationMember.organization"`)
	}
	return nil
}

func (omu *OrganizationMemberUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := omu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationmember.Table, organizationmember.Columns, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt))
	if ps := omu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := omu.mutation.Role(); ok {
		_spec.SetField(organizationmember.FieldRole, field.TypeEnum, value)
	}
	if omu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.UserTable,
			Columns: []string{organizationmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := omu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.UserTable,
			Columns: []string{organizationmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if omu.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.OrganizationTable,
			Columns: []string{organizationmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := omu.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.OrganizationTable,
			Columns: []string{organizationmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, omu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	omu.mutation.done = true
	return n, nil
}

// OrganizationMemberUpdateOne is the builder for updating a single OrganizationMember entity.
type OrganizationMemberUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationMemberMutation
}

// SetUserID sets the "user_id" field.
func (omuo *OrganizationMemberUpdateOne) SetUserID(u uuid.UUID) *OrganizationMemberUpdateOne {
	omuo.mutation.SetUserID(u)
	return omuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (omuo *OrganizationMemberUpdateOne) SetNillableUserID(u *uuid.UUID) *OrganizationMemberUpdateOne {
	if u != nil {
		omuo.SetUserID(*u)
	}
	return omuo
}

// SetOrganizationID sets the "organization_id" field.
func (omuo *OrganizationMemberUpdateOne) SetOrganizationID(u uuid.UUID) *OrganizationMemberUpdateOne {
	omuo.mutation.SetOrganizationID(u)
	return omuo
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (omuo *OrganizationMemberUpdateOne) SetNillableOrganizationID(u *uuid.UUID) *OrganizationMemberUpdateOne {
	if u != nil {
		omuo.SetOrganizationID(*u)
	}
	return omuo
}

// SetRole sets the "role" field.
func (omuo *OrganizationMemberUpdateOne) SetRole(o organizationmember.Role) *OrganizationMemberUpdateOne {
	omuo.mutation.SetRole(o)
	return omuo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (omuo *OrganizationMemberUpdateOne) SetNillableRole(o *organizationmember.Role) *OrganizationMemberUpdateOne {
	if o != nil {
		omuo.SetRole(*o)
	}
	return omuo
}

// SetUser sets the "user" edge to the User entity.
func (omuo *OrganizationMemberUpdateOne) SetUser(u *User) *OrganizationMemberUpdateOne {
	return omuo.SetUserID(u.ID)
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (omuo *OrganizationMemberUpdateOne) SetOrganization(o *Organization) *OrganizationMemberUpdateOne {
	return omuo.SetOrganizationID(o.ID)
}

// Mutation returns the OrganizationMemberMutation object of the builder.
func (omuo *OrganizationMemberUpdateOne) Mutation() *OrganizationMemberMutation {
	return omuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (omuo *OrganizationMemberUpdateOne) ClearUser() *OrganizationMemberUpdateOne {
	omuo.mutation.ClearUser()
	return omuo
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (omuo *OrganizationMemberUpdateOne) ClearOrganization() *OrganizationMemberUpdateOne {
	omuo.mutation.ClearOrganization()
	return omuo
}

// Where appends a list predicates to the OrganizationMemberUpdate builder.
func (omuo *OrganizationMemberUpdateOne) Where(ps ...predicate.OrganizationMember) *OrganizationMemberUpdateOne {
	omuo.mutation.Where(ps...)
	return omuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (omuo *OrganizationMemberUpdateOne) Select(field string, fields ...string) *OrganizationMemberUpdateOne {
	omuo.fields = append([]string{field}, fields...)
	return omuo
}

// Save executes the query and returns the updated OrganizationMember entity.
func (omuo *OrganizationMemberUpdateOne) Save(ctx context.Context) (*OrganizationMember, error) {
	return withHooks(ctx, omuo.sqlSave, omuo.mutation, omuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (omuo *OrganizationMemberUpdateOne) SaveX(ctx context.Context) *OrganizationMember {
	node, err := omuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (omuo *OrganizationMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := omuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (omuo *OrganizationMemberUpdateOne) ExecX(ctx context.Context) {
	if err := omuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (omuo *OrganizationMemberUpdateOne) check() error {
	if v, ok := omuo.mutation.Role(); ok {
		if err := organizationmember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "OrganizationMember.role": %w`, err)}
		}
	}
	if omuo.mutation.UserCleared() && len(omuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationMember.user"`)
	}
	if omuo.mutation.OrganizationCleared() && len(omuo.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrganizationMember.organization"`)
	}
	return nil
}

func (omuo *OrganizationMemberUpdateOne) sqlSave(ctx context.Context) (_node *OrganizationMember, err error) {
	if err := omuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organizationmember.Table, organizationmember.Columns, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt))
	id, ok := omuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrganizationMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := omuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationmember.FieldID)
		for _, f := range fields {
			if !organizationmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organizationmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := omuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := omuo.mutation.Role(); ok {
		_spec.SetField(organizationmember.FieldRole, field.TypeEnum, value)
	}
	if omuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.UserTable,
			Columns: []string{organizationmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := omuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.UserTable,
			Columns: []string{organizationmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if omuo.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.OrganizationTable,
			Columns: []string{organizationmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := omuo.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   organizationmember.OrganizationTable,
			Columns: []string{organizationmember.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrganizationMember{config: omuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, omuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organizationmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	omuo.mutation.done = true
	return _node, nil
}
