// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/organization"
	"backend/ent/organizationmember"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// OrganizationMemberQuery is the builder for querying OrganizationMember entities.
type OrganizationMemberQuery struct {
	config
	ctx              *QueryContext
	order            []organizationmember.OrderOption
	inters           []Interceptor
	predicates       []predicate.OrganizationMember
	withUser         *UserQuery
	withOrganization *OrganizationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrganizationMemberQuery builder.
func (omq *OrganizationMemberQuery) Where(ps ...predicate.OrganizationMember) *OrganizationMemberQuery {
	omq.predicates = append(omq.predicates, ps...)
	return omq
}

// Limit the number of records to be returned by this query.
func (omq *OrganizationMemberQuery) Limit(limit int) *OrganizationMemberQuery {
	omq.ctx.Limit = &limit
	return omq
}

// Offset to start from.
func (omq *OrganizationMemberQuery) Offset(offset int) *OrganizationMemberQuery {
	omq.ctx.Offset = &offset
	return omq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (omq *OrganizationMemberQuery) Unique(unique bool) *OrganizationMemberQuery {
	omq.ctx.Unique = &unique
	return omq
}

// Order specifies how the records should be ordered.
func (omq *OrganizationMemberQuery) Order(o ...organizationmember.OrderOption) *OrganizationMemberQuery {
	omq.order = append(omq.order, o...)
	return omq
}

// QueryUser chains the current query on the "user" edge.
func (omq *OrganizationMemberQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: omq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := omq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := omq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(organizationmember.Table, organizationmember.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, organizationmember.UserTable, organizationmember.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(omq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrganization chains the current query on the "organization" edge.
func (omq *OrganizationMemberQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: omq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := omq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := omq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(organizationmember.Table, organizationmember.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, organizationmember.OrganizationTable, organizationmember.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(omq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrganizationMember entity from the query.
// Returns a *NotFoundError when no OrganizationMember was found.
func (omq *OrganizationMemberQuery) First(ctx context.Context) (*OrganizationMember, error) {
	nodes, err := omq.Limit(1).All(setContextOp(ctx, omq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{organizationmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (omq *OrganizationMemberQuery) FirstX(ctx context.Context) *OrganizationMember {
	node, err := omq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrganizationMember ID from the query.
// Returns a *NotFoundError when no OrganizationMember ID was found.
func (omq *OrganizationMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = omq.Limit(1).IDs(setContextOp(ctx, omq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{organizationmember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (omq *OrganizationMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := omq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrganizationMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrganizationMember entity is found.
// Returns a *NotFoundError when no OrganizationMember entities are found.
func (omq *OrganizationMemberQuery) Only(ctx context.Context) (*OrganizationMember, error) {
	nodes, err := omq.Limit(2).All(setContextOp(ctx, omq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{organizationmember.Label}
	default:
		return nil, &NotSingularError{organizationmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (omq *OrganizationMemberQuery) OnlyX(ctx context.Context) *OrganizationMember {
	node, err := omq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrganizationMember ID in the query.
// Returns a *NotSingularError when more than one OrganizationMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (omq *OrganizationMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = omq.Limit(2).IDs(setContextOp(ctx, omq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{organizationmember.Label}
	default:
		err = &NotSingularError{organizationmember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (omq *OrganizationMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := omq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrganizationMembers.
func (omq *OrganizationMemberQuery) All(ctx context.Context) ([]*OrganizationMember, error) {
	ctx = setContextOp(ctx, omq.ctx, ent.OpQueryAll)
	if err := omq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrganizationMember, *OrganizationMemberQuery]()
	return withInterceptors[[]*OrganizationMember](ctx, omq, qr, omq.inters)
}

// AllX is like All, but panics if an error occurs.
func (omq *OrganizationMemberQuery) AllX(ctx context.Context) []*OrganizationMember {
	nodes, err := omq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrganizationMember IDs.
func (omq *OrganizationMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if omq.ctx.Unique == nil && omq.path != nil {
		omq.Unique(true)
	}
	ctx = setContextOp(ctx, omq.ctx, ent.OpQueryIDs)
	if err = omq.Select(organizationmember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (omq *OrganizationMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := omq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (omq *OrganizationMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, omq.ctx, ent.OpQueryCount)
	if err := omq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, omq, querierCount[*OrganizationMemberQuery](), omq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (omq *OrganizationMemberQuery) CountX(ctx context.Context) int {
	count, err := omq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (omq *OrganizationMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, omq.ctx, ent.OpQueryExist)
	switch _, err := omq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (omq *OrganizationMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := omq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrganizationMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (omq *OrganizationMemberQuery) Clone() *OrganizationMemberQuery {
	if omq == nil {
		return nil
	}
	return &OrganizationMemberQuery{
		config:           omq.config,
		ctx:              omq.ctx.Clone(),
		order:            append([]organizationmember.OrderOption{}, omq.order...),
		inters:           append([]Interceptor{}, omq.inters...),
		predicates:       append([]predicate.OrganizationMember{}, omq.predicates...),
		withUser:         omq.withUser.Clone(),
		withOrganization: omq.withOrganization.Clone(),
		// clone intermediate query.
		sql:  omq.sql.Clone(),
		path: omq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (omq *OrganizationMemberQuery) WithUser(opts ...func(*UserQuery)) *OrganizationMemberQuery {
	query := (&UserClient{config: omq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	omq.withUser = query
	return omq
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (omq *OrganizationMemberQuery) WithOrganization(opts ...func(*OrganizationQuery)) *OrganizationMemberQuery {
	query := (&OrganizationClient{config: omq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	omq.withOrganization = query
	return omq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrganizationMember.Query().
//		GroupBy(organizationmember.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (omq *OrganizationMemberQuery) GroupBy(field string, fields ...string) *OrganizationMemberGroupBy {
	omq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrganizationMemberGroupBy{build: omq}
	grbuild.flds = &omq.ctx.Fields
	grbuild.label = organizationmember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.OrganizationMember.Query().
//		Select(organizationmember.FieldUserID).
//		Scan(ctx, &v)
func (omq *OrganizationMemberQuery) Select(fields ...string) *OrganizationMemberSelect {
	omq.ctx.Fields = append(omq.ctx.Fields, fields...)
	sbuild := &OrganizationMemberSelect{OrganizationMemberQuery: omq}
	sbuild.label = organizationmember.Label
	sbuild.flds, sbuild.scan = &omq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrganizationMemberSelect configured with the given aggregations.
func (omq *OrganizationMemberQuery) Aggregate(fns ...AggregateFunc) *OrganizationMemberSelect {
	return omq.Select().Aggregate(fns...)
}

func (omq *OrganizationMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range omq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, omq); err != nil {
				return err
			}
		}
	}
	for _, f := range omq.ctx.Fields {
		if !organizationmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if omq.path != nil {
		prev, err := omq.path(ctx)
		if err != nil {
			return err
		}
		omq.sql = prev
	}
	return nil
}

func (omq *OrganizationMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrganizationMember, error) {
	var (
		nodes       = []*OrganizationMember{}
		_spec       = omq.querySpec()
		loadedTypes = [2]bool{
			omq.withUser != nil,
			omq.withOrganization != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrganizationMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrganizationMember{config: omq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, omq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := omq.withUser; query != nil {
		if err := omq.loadUser(ctx, query, nodes, nil,
			func(n *OrganizationMember, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := omq.withOrganization; query != nil {
		if err := omq.loadOrganization(ctx, query, nodes, nil,
			func(n *OrganizationMember, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (omq *OrganizationMemberQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*OrganizationMember, init func(*OrganizationMember), assign func(*OrganizationMember, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OrganizationMember)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (omq *OrganizationMemberQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*OrganizationMember, init func(*OrganizationMember), assign func(*OrganizationMember, *Organization)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OrganizationMember)
	for i := range nodes {
		fk := nodes[i].OrganizationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "organization_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (omq *OrganizationMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := omq.querySpec()
	_spec.Node.Columns = omq.ctx.Fields
	if len(omq.ctx.Fields) > 0 {
		_spec.Unique = omq.ctx.Unique != nil && *omq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, omq.driver, _spec)
}

func (omq *OrganizationMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(organizationmember.Table, organizationmember.Columns, sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeInt))
	_spec.From = omq.sql
	if unique := omq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if omq.path != nil {
		_spec.Unique = true
	}
	if fields := omq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organizationmember.FieldID)
		for i := range fields {
			if fields[i] != organizationmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if omq.withUser != nil {
			_spec.Node.AddColumnOnce(organizationmember.FieldUserID)
		}
		if omq.withOrganization != nil {
			_spec.Node.AddColumnOnce(organizationmember.FieldOrganizationID)
		}
	}
	if ps := omq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := omq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := omq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := omq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (omq *OrganizationMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(omq.driver.Dialect())
	t1 := builder.Table(organizationmember.Table)
	columns := omq.ctx.Fields
	if len(columns) == 0 {
		columns = organizationmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if omq.sql != nil {
		selector = omq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if omq.ctx.Unique != nil && *omq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range omq.predicates {
		p(selector)
	}
	for _, p := range omq.order {
		p(selector)
	}
	if offset := omq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := omq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// OrganizationMemberGroupBy is the group-by builder for OrganizationMember entities.
type OrganizationMemberGroupBy struct {
	selector
	build *OrganizationMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (omgb *OrganizationMemberGroupBy) Aggregate(fns ...AggregateFunc) *OrganizationMemberGroupBy {
	omgb.fns = append(omgb.fns, fns...)
	return omgb
}

// Scan applies the selector query and scans the result into the given value.
func (omgb *OrganizationMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, omgb.build.ctx, ent.OpQueryGroupBy)
	if err := omgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrganizationMemberQuery, *OrganizationMemberGroupBy](ctx, omgb.build, omgb, omgb.build.inters, v)
}

func (omgb *OrganizationMemberGroupBy) sqlScan(ctx context.Context, root *OrganizationMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(omgb.fns))
	for _, fn := range omgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*omgb.flds)+len(omgb.fns))
		for _, f := range *omgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*omgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := omgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrganizationMemberSelect is the builder for selecting fields of OrganizationMember entities.
type OrganizationMemberSelect struct {
	*OrganizationMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (oms *OrganizationMemberSelect) Aggregate(fns ...AggregateFunc) *OrganizationMemberSelect {
	oms.fns = append(oms.fns, fns...)
	return oms
}

// Scan applies the selector query and scans the result into the given value.
func (oms *OrganizationMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, oms.ctx, ent.OpQuerySelect)
	if err := oms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrganizationMemberQuery, *OrganizationMemberSelect](ctx, oms.OrganizationMemberQuery, oms, oms.inters, v)
}

func (oms *OrganizationMemberSelect) sqlScan(ctx context.Context, root *OrganizationMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(oms.fns))
	for _, fn := range oms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*oms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := oms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
