// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/project"
	"backend/ent/projectmember"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProjectMemberCreate is the builder for creating a ProjectMember entity.
type ProjectMemberCreate struct {
	config
	mutation *ProjectMemberMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (pmc *ProjectMemberCreate) SetUserID(u uuid.UUID) *ProjectMemberCreate {
	pmc.mutation.SetUserID(u)
	return pmc
}

// SetProjectID sets the "project_id" field.
func (pmc *ProjectMemberCreate) SetProjectID(u uuid.UUID) *ProjectMemberCreate {
	pmc.mutation.SetProjectID(u)
	return pmc
}

// SetPermission sets the "permission" field.
func (pmc *ProjectMemberCreate) SetPermission(pr projectmember.Permission) *ProjectMemberCreate {
	pmc.mutation.SetPermission(pr)
	return pmc
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (pmc *ProjectMemberCreate) SetNillablePermission(pr *projectmember.Permission) *ProjectMemberCreate {
	if pr != nil {
		pmc.SetPermission(*pr)
	}
	return pmc
}

// SetCreatedAt sets the "created_at" field.
func (pmc *ProjectMemberCreate) SetCreatedAt(t time.Time) *ProjectMemberCreate {
	pmc.mutation.SetCreatedAt(t)
	return pmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pmc *ProjectMemberCreate) SetNillableCreatedAt(t *time.Time) *ProjectMemberCreate {
	if t != nil {
		pmc.SetCreatedAt(*t)
	}
	return pmc
}

// SetUser sets the "user" edge to the User entity.
func (pmc *ProjectMemberCreate) SetUser(u *User) *ProjectMemberCreate {
	return pmc.SetUserID(u.ID)
}

// SetProject sets the "project" edge to the Project entity.
func (pmc *ProjectMemberCreate) SetProject(p *Project) *ProjectMemberCreate {
	return pmc.SetProjectID(p.ID)
}

// Mutation returns the ProjectMemberMutation object of the builder.
func (pmc *ProjectMemberCreate) Mutation() *ProjectMemberMutation {
	return pmc.mutation
}

// Save creates the ProjectMember in the database.
func (pmc *ProjectMemberCreate) Save(ctx context.Context) (*ProjectMember, error) {
	pmc.defaults()
	return withHooks(ctx, pmc.sqlSave, pmc.mutation, pmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (pmc *ProjectMemberCreate) SaveX(ctx context.Context) *ProjectMember {
	v, err := pmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pmc *ProjectMemberCreate) Exec(ctx context.Context) error {
	_, err := pmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmc *ProjectMemberCreate) ExecX(ctx context.Context) {
	if err := pmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pmc *ProjectMemberCreate) defaults() {
	if _, ok := pmc.mutation.Permission(); !ok {
		v := projectmember.DefaultPermission
		pmc.mutation.SetPermission(v)
	}
	if _, ok := pmc.mutation.CreatedAt(); !ok {
		v := projectmember.DefaultCreatedAt()
		pmc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pmc *ProjectMemberCreate) check() error {
	if _, ok := pmc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ProjectMember.user_id"`)}
	}
	if _, ok := pmc.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "ProjectMember.project_id"`)}
	}
	if _, ok := pmc.mutation.Permission(); !ok {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required field "ProjectMember.permission"`)}
	}
	if v, ok := pmc.mutation.Permission(); ok {
		if err := projectmember.PermissionValidator(v); err != nil {
			return &ValidationError{Name: "permission", err: fmt.Errorf(`ent: validator failed for field "ProjectMember.permission": %w`, err)}
		}
	}
	if _, ok := pmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ProjectMember.created_at"`)}
	}
	if len(pmc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ProjectMember.user"`)}
	}
	if len(pmc.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "ProjectMember.project"`)}
	}
	return nil
}

func (pmc *ProjectMemberCreate) sqlSave(ctx context.Context) (*ProjectMember, error) {
	if err := pmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := pmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	pmc.mutation.id = &_node.ID
	pmc.mutation.done = true
	return _node, nil
}

func (pmc *ProjectMemberCreate) createSpec() (*ProjectMember, *sqlgraph.CreateSpec) {
	var (
		_node = &ProjectMember{config: pmc.config}
		_spec = sqlgraph.NewCreateSpec(projectmember.Table, sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt))
	)
	if value, ok := pmc.mutation.Permission(); ok {
		_spec.SetField(projectmember.FieldPermission, field.TypeEnum, value)
		_node.Permission = value
	}
	if value, ok := pmc.mutation.CreatedAt(); ok {
		_spec.SetField(projectmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := pmc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectmember.UserTable,
			Columns: []string{projectmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := pmc.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   projectmember.ProjectTable,
			Columns: []string{projectmember.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ProjectMemberCreateBulk is the builder for creating many ProjectMember entities in bulk.
type ProjectMemberCreateBulk struct {
	config
	err      error
	builders []*ProjectMemberCreate
}

// Save creates the ProjectMember entities in the database.
func (pmcb *ProjectMemberCreateBulk) Save(ctx context.Context) ([]*ProjectMember, error) {
	if pmcb.err != nil {
		return nil, pmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(pmcb.builders))
	nodes := make([]*ProjectMember, len(pmcb.builders))
	mutators := make([]Mutator, len(pmcb.builders))
	for i := range pmcb.builders {
		func(i int, root context.Context) {
			builder := pmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ProjectMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pmcb *ProjectMemberCreateBulk) SaveX(ctx context.Context) []*ProjectMember {
	v, err := pmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pmcb *ProjectMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := pmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmcb *ProjectMemberCreateBulk) ExecX(ctx context.Context) {
	if err := pmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
