// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/invite"
	"backend/ent/organization"
	"backend/ent/predicate"
	"backend/ent/project"
	"backend/ent/projectmember"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (pu *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetOrganizationID sets the "organization_id" field.
func (pu *ProjectUpdate) SetOrganizationID(u uuid.UUID) *ProjectUpdate {
	pu.mutation.SetOrganizationID(u)
	return pu
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableOrganizationID(u *uuid.UUID) *ProjectUpdate {
	if u != nil {
		pu.SetOrganizationID(*u)
	}
	return pu
}

// SetName sets the "name" field.
func (pu *ProjectUpdate) SetName(s string) *ProjectUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableName(s *string) *ProjectUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetIsPrivate sets the "is_private" field.
func (pu *ProjectUpdate) SetIsPrivate(b bool) *ProjectUpdate {
	pu.mutation.SetIsPrivate(b)
	return pu
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (pu *ProjectUpdate) SetNillableIsPrivate(b *bool) *ProjectUpdate {
	if b != nil {
		pu.SetIsPrivate(*b)
	}
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProjectUpdate) SetUpdatedAt(t time.Time) *ProjectUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (pu *ProjectUpdate) SetOrganization(o *Organization) *ProjectUpdate {
	return pu.SetOrganizationID(o.ID)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (pu *ProjectUpdate) AddMemberIDs(ids ...uuid.UUID) *ProjectUpdate {
	pu.mutation.AddMemberIDs(ids...)
	return pu
}

// AddMembers adds the "members" edges to the User entity.
func (pu *ProjectUpdate) AddMembers(u ...*User) *ProjectUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pu.AddMemberIDs(ids...)
}

// AddInviteIDs adds the "invites" edge to the Invite entity by IDs.
func (pu *ProjectUpdate) AddInviteIDs(ids ...uuid.UUID) *ProjectUpdate {
	pu.mutation.AddInviteIDs(ids...)
	return pu
}

// AddInvites adds the "invites" edges to the Invite entity.
func (pu *ProjectUpdate) AddInvites(i ...*Invite) *ProjectUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return pu.AddInviteIDs(ids...)
}

// AddLastAccessedByIDs adds the "last_accessed_by" edge to the User entity by IDs.
func (pu *ProjectUpdate) AddLastAccessedByIDs(ids ...uuid.UUID) *ProjectUpdate {
	pu.mutation.AddLastAccessedByIDs(ids...)
	return pu
}

// AddLastAccessedBy adds the "last_accessed_by" edges to the User entity.
func (pu *ProjectUpdate) AddLastAccessedBy(u ...*User) *ProjectUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pu.AddLastAccessedByIDs(ids...)
}

// AddProjectMembershipIDs adds the "project_memberships" edge to the ProjectMember entity by IDs.
func (pu *ProjectUpdate) AddProjectMembershipIDs(ids ...int) *ProjectUpdate {
	pu.mutation.AddProjectMembershipIDs(ids...)
	return pu
}

// AddProjectMemberships adds the "project_memberships" edges to the ProjectMember entity.
func (pu *ProjectUpdate) AddProjectMemberships(p ...*ProjectMember) *ProjectUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddProjectMembershipIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (pu *ProjectUpdate) Mutation() *ProjectMutation {
	return pu.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (pu *ProjectUpdate) ClearOrganization() *ProjectUpdate {
	pu.mutation.ClearOrganization()
	return pu
}

// ClearMembers clears all "members" edges to the User entity.
func (pu *ProjectUpdate) ClearMembers() *ProjectUpdate {
	pu.mutation.ClearMembers()
	return pu
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (pu *ProjectUpdate) RemoveMemberIDs(ids ...uuid.UUID) *ProjectUpdate {
	pu.mutation.RemoveMemberIDs(ids...)
	return pu
}

// RemoveMembers removes "members" edges to User entities.
func (pu *ProjectUpdate) RemoveMembers(u ...*User) *ProjectUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pu.RemoveMemberIDs(ids...)
}

// ClearInvites clears all "invites" edges to the Invite entity.
func (pu *ProjectUpdate) ClearInvites() *ProjectUpdate {
	pu.mutation.ClearInvites()
	return pu
}

// RemoveInviteIDs removes the "invites" edge to Invite entities by IDs.
func (pu *ProjectUpdate) RemoveInviteIDs(ids ...uuid.UUID) *ProjectUpdate {
	pu.mutation.RemoveInviteIDs(ids...)
	return pu
}

// RemoveInvites removes "invites" edges to Invite entities.
func (pu *ProjectUpdate) RemoveInvites(i ...*Invite) *ProjectUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return pu.RemoveInviteIDs(ids...)
}

// ClearLastAccessedBy clears all "last_accessed_by" edges to the User entity.
func (pu *ProjectUpdate) ClearLastAccessedBy() *ProjectUpdate {
	pu.mutation.ClearLastAccessedBy()
	return pu
}

// RemoveLastAccessedByIDs removes the "last_accessed_by" edge to User entities by IDs.
func (pu *ProjectUpdate) RemoveLastAccessedByIDs(ids ...uuid.UUID) *ProjectUpdate {
	pu.mutation.RemoveLastAccessedByIDs(ids...)
	return pu
}

// RemoveLastAccessedBy removes "last_accessed_by" edges to User entities.
func (pu *ProjectUpdate) RemoveLastAccessedBy(u ...*User) *ProjectUpdate {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pu.RemoveLastAccessedByIDs(ids...)
}

// ClearProjectMemberships clears all "project_memberships" edges to the ProjectMember entity.
func (pu *ProjectUpdate) ClearProjectMemberships() *ProjectUpdate {
	pu.mutation.ClearProjectMemberships()
	return pu
}

// RemoveProjectMembershipIDs removes the "project_memberships" edge to ProjectMember entities by IDs.
func (pu *ProjectUpdate) RemoveProjectMembershipIDs(ids ...int) *ProjectUpdate {
	pu.mutation.RemoveProjectMembershipIDs(ids...)
	return pu
}

// RemoveProjectMemberships removes "project_memberships" edges to ProjectMember entities.
func (pu *ProjectUpdate) RemoveProjectMemberships(p ...*ProjectMember) *ProjectUpdate {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemoveProjectMembershipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProjectUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProjectUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProjectUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProjectUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if pu.mutation.OrganizationCleared() && len(pu.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.organization"`)
	}
	return nil
}

func (pu *ProjectUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.IsPrivate(); ok {
		_spec.SetField(project.FieldIsPrivate, field.TypeBool, value)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if pu.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   project.MembersTable,
			Columns: project.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		createE := &ProjectMemberCreate{config: pu.config, mutation: newProjectMemberMutation(pu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedMembersIDs(); len(nodes) > 0 && !pu.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   project.MembersTable,
			Columns: project.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectMemberCreate{config: pu.config, mutation: newProjectMemberMutation(pu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   project.MembersTable,
			Columns: project.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectMemberCreate{config: pu.config, mutation: newProjectMemberMutation(pu.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedInvitesIDs(); len(nodes) > 0 && !pu.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.LastAccessedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.LastAccessedByTable,
			Columns: []string{project.LastAccessedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedLastAccessedByIDs(); len(nodes) > 0 && !pu.mutation.LastAccessedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.LastAccessedByTable,
			Columns: []string{project.LastAccessedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.LastAccessedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.LastAccessedByTable,
			Columns: []string{project.LastAccessedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.ProjectMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.ProjectMembershipsTable,
			Columns: []string{project.ProjectMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedProjectMembershipsIDs(); len(nodes) > 0 && !pu.mutation.ProjectMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.ProjectMembershipsTable,
			Columns: []string{project.ProjectMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.ProjectMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.ProjectMembershipsTable,
			Columns: []string{project.ProjectMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetOrganizationID sets the "organization_id" field.
func (puo *ProjectUpdateOne) SetOrganizationID(u uuid.UUID) *ProjectUpdateOne {
	puo.mutation.SetOrganizationID(u)
	return puo
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableOrganizationID(u *uuid.UUID) *ProjectUpdateOne {
	if u != nil {
		puo.SetOrganizationID(*u)
	}
	return puo
}

// SetName sets the "name" field.
func (puo *ProjectUpdateOne) SetName(s string) *ProjectUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableName(s *string) *ProjectUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetIsPrivate sets the "is_private" field.
func (puo *ProjectUpdateOne) SetIsPrivate(b bool) *ProjectUpdateOne {
	puo.mutation.SetIsPrivate(b)
	return puo
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (puo *ProjectUpdateOne) SetNillableIsPrivate(b *bool) *ProjectUpdateOne {
	if b != nil {
		puo.SetIsPrivate(*b)
	}
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProjectUpdateOne) SetUpdatedAt(t time.Time) *ProjectUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (puo *ProjectUpdateOne) SetOrganization(o *Organization) *ProjectUpdateOne {
	return puo.SetOrganizationID(o.ID)
}

// AddMemberIDs adds the "members" edge to the User entity by IDs.
func (puo *ProjectUpdateOne) AddMemberIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	puo.mutation.AddMemberIDs(ids...)
	return puo
}

// AddMembers adds the "members" edges to the User entity.
func (puo *ProjectUpdateOne) AddMembers(u ...*User) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return puo.AddMemberIDs(ids...)
}

// AddInviteIDs adds the "invites" edge to the Invite entity by IDs.
func (puo *ProjectUpdateOne) AddInviteIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	puo.mutation.AddInviteIDs(ids...)
	return puo
}

// AddInvites adds the "invites" edges to the Invite entity.
func (puo *ProjectUpdateOne) AddInvites(i ...*Invite) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return puo.AddInviteIDs(ids...)
}

// AddLastAccessedByIDs adds the "last_accessed_by" edge to the User entity by IDs.
func (puo *ProjectUpdateOne) AddLastAccessedByIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	puo.mutation.AddLastAccessedByIDs(ids...)
	return puo
}

// AddLastAccessedBy adds the "last_accessed_by" edges to the User entity.
func (puo *ProjectUpdateOne) AddLastAccessedBy(u ...*User) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return puo.AddLastAccessedByIDs(ids...)
}

// AddProjectMembershipIDs adds the "project_memberships" edge to the ProjectMember entity by IDs.
func (puo *ProjectUpdateOne) AddProjectMembershipIDs(ids ...int) *ProjectUpdateOne {
	puo.mutation.AddProjectMembershipIDs(ids...)
	return puo
}

// AddProjectMemberships adds the "project_memberships" edges to the ProjectMember entity.
func (puo *ProjectUpdateOne) AddProjectMemberships(p ...*ProjectMember) *ProjectUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddProjectMembershipIDs(ids...)
}

// Mutation returns the ProjectMutation object of the builder.
func (puo *ProjectUpdateOne) Mutation() *ProjectMutation {
	return puo.mutation
}

// ClearOrganization clears the "organization" edge to the Organization entity.
func (puo *ProjectUpdateOne) ClearOrganization() *ProjectUpdateOne {
	puo.mutation.ClearOrganization()
	return puo
}

// ClearMembers clears all "members" edges to the User entity.
func (puo *ProjectUpdateOne) ClearMembers() *ProjectUpdateOne {
	puo.mutation.ClearMembers()
	return puo
}

// RemoveMemberIDs removes the "members" edge to User entities by IDs.
func (puo *ProjectUpdateOne) RemoveMemberIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	puo.mutation.RemoveMemberIDs(ids...)
	return puo
}

// RemoveMembers removes "members" edges to User entities.
func (puo *ProjectUpdateOne) RemoveMembers(u ...*User) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return puo.RemoveMemberIDs(ids...)
}

// ClearInvites clears all "invites" edges to the Invite entity.
func (puo *ProjectUpdateOne) ClearInvites() *ProjectUpdateOne {
	puo.mutation.ClearInvites()
	return puo
}

// RemoveInviteIDs removes the "invites" edge to Invite entities by IDs.
func (puo *ProjectUpdateOne) RemoveInviteIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	puo.mutation.RemoveInviteIDs(ids...)
	return puo
}

// RemoveInvites removes "invites" edges to Invite entities.
func (puo *ProjectUpdateOne) RemoveInvites(i ...*Invite) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return puo.RemoveInviteIDs(ids...)
}

// ClearLastAccessedBy clears all "last_accessed_by" edges to the User entity.
func (puo *ProjectUpdateOne) ClearLastAccessedBy() *ProjectUpdateOne {
	puo.mutation.ClearLastAccessedBy()
	return puo
}

// RemoveLastAccessedByIDs removes the "last_accessed_by" edge to User entities by IDs.
func (puo *ProjectUpdateOne) RemoveLastAccessedByIDs(ids ...uuid.UUID) *ProjectUpdateOne {
	puo.mutation.RemoveLastAccessedByIDs(ids...)
	return puo
}

// RemoveLastAccessedBy removes "last_accessed_by" edges to User entities.
func (puo *ProjectUpdateOne) RemoveLastAccessedBy(u ...*User) *ProjectUpdateOne {
	ids := make([]uuid.UUID, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return puo.RemoveLastAccessedByIDs(ids...)
}

// ClearProjectMemberships clears all "project_memberships" edges to the ProjectMember entity.
func (puo *ProjectUpdateOne) ClearProjectMemberships() *ProjectUpdateOne {
	puo.mutation.ClearProjectMemberships()
	return puo
}

// RemoveProjectMembershipIDs removes the "project_memberships" edge to ProjectMember entities by IDs.
func (puo *ProjectUpdateOne) RemoveProjectMembershipIDs(ids ...int) *ProjectUpdateOne {
	puo.mutation.RemoveProjectMembershipIDs(ids...)
	return puo
}

// RemoveProjectMemberships removes "project_memberships" edges to ProjectMember entities.
func (puo *ProjectUpdateOne) RemoveProjectMemberships(p ...*ProjectMember) *ProjectUpdateOne {
	ids := make([]int, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemoveProjectMembershipIDs(ids...)
}

// Where appends a list predicates to the ProjectUpdate builder.
func (puo *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Project entity.
func (puo *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProjectUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := project.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProjectUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := project.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Project.name": %w`, err)}
		}
	}
	if puo.mutation.OrganizationCleared() && len(puo.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Project.organization"`)
	}
	return nil
}

func (puo *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeUUID))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.IsPrivate(); ok {
		_spec.SetField(project.FieldIsPrivate, field.TypeBool, value)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(project.FieldUpdatedAt, field.TypeTime, value)
	}
	if puo.mutation.OrganizationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   project.OrganizationTable,
			Columns: []string{project.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   project.MembersTable,
			Columns: project.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		createE := &ProjectMemberCreate{config: puo.config, mutation: newProjectMemberMutation(puo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedMembersIDs(); len(nodes) > 0 && !puo.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   project.MembersTable,
			Columns: project.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectMemberCreate{config: puo.config, mutation: newProjectMemberMutation(puo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   project.MembersTable,
			Columns: project.MembersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &ProjectMemberCreate{config: puo.config, mutation: newProjectMemberMutation(puo.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedInvitesIDs(); len(nodes) > 0 && !puo.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   project.InvitesTable,
			Columns: []string{project.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.LastAccessedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.LastAccessedByTable,
			Columns: []string{project.LastAccessedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedLastAccessedByIDs(); len(nodes) > 0 && !puo.mutation.LastAccessedByCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.LastAccessedByTable,
			Columns: []string{project.LastAccessedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.LastAccessedByIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.LastAccessedByTable,
			Columns: []string{project.LastAccessedByColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.ProjectMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.ProjectMembershipsTable,
			Columns: []string{project.ProjectMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedProjectMembershipsIDs(); len(nodes) > 0 && !puo.mutation.ProjectMembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.ProjectMembershipsTable,
			Columns: []string{project.ProjectMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.ProjectMembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   project.ProjectMembershipsTable,
			Columns: []string{project.ProjectMembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(projectmember.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Project{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
