// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/organization"
	"backend/ent/project"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// LastOrgID holds the value of the "last_org_id" field.
	LastOrgID *uuid.UUID `json:"last_org_id,omitempty"`
	// LastProjectID holds the value of the "last_project_id" field.
	LastProjectID *uuid.UUID `json:"last_project_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Organizations holds the value of the organizations edge.
	Organizations []*Organization `json:"organizations,omitempty"`
	// Projects holds the value of the projects edge.
	Projects []*Project `json:"projects,omitempty"`
	// SentInvites holds the value of the sent_invites edge.
	SentInvites []*Invite `json:"sent_invites,omitempty"`
	// LastOrganization holds the value of the last_organization edge.
	LastOrganization *Organization `json:"last_organization,omitempty"`
	// LastProject holds the value of the last_project edge.
	LastProject *Project `json:"last_project,omitempty"`
	// OrganizationMemberships holds the value of the organization_memberships edge.
	OrganizationMemberships []*OrganizationMember `json:"organization_memberships,omitempty"`
	// ProjectMemberships holds the value of the project_memberships edge.
	ProjectMemberships []*ProjectMember `json:"project_memberships,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// OrganizationsOrErr returns the Organizations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OrganizationsOrErr() ([]*Organization, error) {
	if e.loadedTypes[0] {
		return e.Organizations, nil
	}
	return nil, &NotLoadedError{edge: "organizations"}
}

// ProjectsOrErr returns the Projects value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[1] {
		return e.Projects, nil
	}
	return nil, &NotLoadedError{edge: "projects"}
}

// SentInvitesOrErr returns the SentInvites value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SentInvitesOrErr() ([]*Invite, error) {
	if e.loadedTypes[2] {
		return e.SentInvites, nil
	}
	return nil, &NotLoadedError{edge: "sent_invites"}
}

// LastOrganizationOrErr returns the LastOrganization value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) LastOrganizationOrErr() (*Organization, error) {
	if e.LastOrganization != nil {
		return e.LastOrganization, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: organization.Label}
	}
	return nil, &NotLoadedError{edge: "last_organization"}
}

// LastProjectOrErr returns the LastProject value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) LastProjectOrErr() (*Project, error) {
	if e.LastProject != nil {
		return e.LastProject, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "last_project"}
}

// OrganizationMembershipsOrErr returns the OrganizationMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) OrganizationMembershipsOrErr() ([]*OrganizationMember, error) {
	if e.loadedTypes[5] {
		return e.OrganizationMemberships, nil
	}
	return nil, &NotLoadedError{edge: "organization_memberships"}
}

// ProjectMembershipsOrErr returns the ProjectMemberships value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ProjectMembershipsOrErr() ([]*ProjectMember, error) {
	if e.loadedTypes[6] {
		return e.ProjectMemberships, nil
	}
	return nil, &NotLoadedError{edge: "project_memberships"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldLastOrgID, user.FieldLastProjectID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case user.FieldEmail, user.FieldPasswordHash, user.FieldDisplayName:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case user.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				u.ID = *value
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				u.Email = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				u.PasswordHash = value.String
			}
		case user.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				u.DisplayName = value.String
			}
		case user.FieldLastOrgID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field last_org_id", values[i])
			} else if value.Valid {
				u.LastOrgID = new(uuid.UUID)
				*u.LastOrgID = *value.S.(*uuid.UUID)
			}
		case user.FieldLastProjectID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field last_project_id", values[i])
			} else if value.Valid {
				u.LastProjectID = new(uuid.UUID)
				*u.LastProjectID = *value.S.(*uuid.UUID)
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				u.UpdatedAt = value.Time
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryOrganizations queries the "organizations" edge of the User entity.
func (u *User) QueryOrganizations() *OrganizationQuery {
	return NewUserClient(u.config).QueryOrganizations(u)
}

// QueryProjects queries the "projects" edge of the User entity.
func (u *User) QueryProjects() *ProjectQuery {
	return NewUserClient(u.config).QueryProjects(u)
}

// QuerySentInvites queries the "sent_invites" edge of the User entity.
func (u *User) QuerySentInvites() *InviteQuery {
	return NewUserClient(u.config).QuerySentInvites(u)
}

// QueryLastOrganization queries the "last_organization" edge of the User entity.
func (u *User) QueryLastOrganization() *OrganizationQuery {
	return NewUserClient(u.config).QueryLastOrganization(u)
}

// QueryLastProject queries the "last_project" edge of the User entity.
func (u *User) QueryLastProject() *ProjectQuery {
	return NewUserClient(u.config).QueryLastProject(u)
}

// QueryOrganizationMemberships queries the "organization_memberships" edge of the User entity.
func (u *User) QueryOrganizationMemberships() *OrganizationMemberQuery {
	return NewUserClient(u.config).QueryOrganizationMemberships(u)
}

// QueryProjectMemberships queries the "project_memberships" edge of the User entity.
func (u *User) QueryProjectMemberships() *ProjectMemberQuery {
	return NewUserClient(u.config).QueryProjectMemberships(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("email=")
	builder.WriteString(u.Email)
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(u.DisplayName)
	builder.WriteString(", ")
	if v := u.LastOrgID; v != nil {
		builder.WriteString("last_org_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := u.LastProjectID; v != nil {
		builder.WriteString("last_project_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(u.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
