// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InvitesColumns holds the columns for the "invites" table.
	InvitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "admin", "member"}, Default: "member"},
		{Name: "project_permission", Type: field.TypeEnum, Nullable: true, Enums: []string{"edit", "view"}, Default: "view"},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "used_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID, Nullable: true},
		{Name: "invited_by_id", Type: field.TypeUUID},
	}
	// InvitesTable holds the schema information for the "invites" table.
	InvitesTable = &schema.Table{
		Name:       "invites",
		Columns:    InvitesColumns,
		PrimaryKey: []*schema.Column{InvitesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invites_organizations_invites",
				Columns:    []*schema.Column{InvitesColumns[8]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "invites_projects_invites",
				Columns:    []*schema.Column{InvitesColumns[9]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "invites_users_sent_invites",
				Columns:    []*schema.Column{InvitesColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invite_token",
				Unique:  true,
				Columns: []*schema.Column{InvitesColumns[1]},
			},
			{
				Name:    "invite_email_organization_id",
				Unique:  false,
				Columns: []*schema.Column{InvitesColumns[2], InvitesColumns[8]},
			},
		},
	}
	// OrganizationsColumns holds the columns for the "organizations" table.
	OrganizationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OrganizationsTable holds the schema information for the "organizations" table.
	OrganizationsTable = &schema.Table{
		Name:       "organizations",
		Columns:    OrganizationsColumns,
		PrimaryKey: []*schema.Column{OrganizationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "organization_slug",
				Unique:  true,
				Columns: []*schema.Column{OrganizationsColumns[2]},
			},
		},
	}
	// OrganizationMembersColumns holds the columns for the "organization_members" table.
	OrganizationMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"owner", "admin", "member"}, Default: "member"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// OrganizationMembersTable holds the schema information for the "organization_members" table.
	OrganizationMembersTable = &schema.Table{
		Name:       "organization_members",
		Columns:    OrganizationMembersColumns,
		PrimaryKey: []*schema.Column{OrganizationMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "organization_members_users_user",
				Columns:    []*schema.Column{OrganizationMembersColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "organization_members_organizations_organization",
				Columns:    []*schema.Column{OrganizationMembersColumns[4]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "organizationmember_user_id_organization_id",
				Unique:  true,
				Columns: []*schema.Column{OrganizationMembersColumns[3], OrganizationMembersColumns[4]},
			},
		},
	}
	// ProjectsColumns holds the columns for the "projects" table.
	ProjectsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "is_private", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "organization_id", Type: field.TypeUUID},
	}
	// ProjectsTable holds the schema information for the "projects" table.
	ProjectsTable = &schema.Table{
		Name:       "projects",
		Columns:    ProjectsColumns,
		PrimaryKey: []*schema.Column{ProjectsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "projects_organizations_projects",
				Columns:    []*schema.Column{ProjectsColumns[5]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "project_organization_id_name",
				Unique:  false,
				Columns: []*schema.Column{ProjectsColumns[5], ProjectsColumns[1]},
			},
		},
	}
	// ProjectMembersColumns holds the columns for the "project_members" table.
	ProjectMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "permission", Type: field.TypeEnum, Enums: []string{"edit", "view"}, Default: "view"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "project_id", Type: field.TypeUUID},
	}
	// ProjectMembersTable holds the schema information for the "project_members" table.
	ProjectMembersTable = &schema.Table{
		Name:       "project_members",
		Columns:    ProjectMembersColumns,
		PrimaryKey: []*schema.Column{ProjectMembersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "project_members_users_user",
				Columns:    []*schema.Column{ProjectMembersColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "project_members_projects_project",
				Columns:    []*schema.Column{ProjectMembersColumns[4]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "projectmember_user_id_project_id",
				Unique:  true,
				Columns: []*schema.Column{ProjectMembersColumns[3], ProjectMembersColumns[4]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "last_org_id", Type: field.TypeUUID, Nullable: true},
		{Name: "last_project_id", Type: field.TypeUUID, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "users_organizations_last_organization",
				Columns:    []*schema.Column{UsersColumns[6]},
				RefColumns: []*schema.Column{OrganizationsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "users_projects_last_project",
				Columns:    []*schema.Column{UsersColumns[7]},
				RefColumns: []*schema.Column{ProjectsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InvitesTable,
		OrganizationsTable,
		OrganizationMembersTable,
		ProjectsTable,
		ProjectMembersTable,
		UsersTable,
	}
)

func init() {
	InvitesTable.ForeignKeys[0].RefTable = OrganizationsTable
	InvitesTable.ForeignKeys[1].RefTable = ProjectsTable
	InvitesTable.ForeignKeys[2].RefTable = UsersTable
	OrganizationMembersTable.ForeignKeys[0].RefTable = UsersTable
	OrganizationMembersTable.ForeignKeys[1].RefTable = OrganizationsTable
	ProjectsTable.ForeignKeys[0].RefTable = OrganizationsTable
	ProjectMembersTable.ForeignKeys[0].RefTable = UsersTable
	ProjectMembersTable.ForeignKeys[1].RefTable = ProjectsTable
	UsersTable.ForeignKeys[0].RefTable = OrganizationsTable
	UsersTable.ForeignKeys[1].RefTable = ProjectsTable
}
