// Code generated by ent, DO NOT EDIT.

package invite

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the invite type in the database.
	Label = "invite"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldProjectPermission holds the string denoting the project_permission field in the database.
	FieldProjectPermission = "project_permission"
	// FieldInvitedByID holds the string denoting the invited_by_id field in the database.
	FieldInvitedByID = "invited_by_id"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeInvitedBy holds the string denoting the invited_by edge name in mutations.
	EdgeInvitedBy = "invited_by"
	// Table holds the table name of the invite in the database.
	Table = "invites"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "invites"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "invites"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// InvitedByTable is the table that holds the invited_by relation/edge.
	InvitedByTable = "invites"
	// InvitedByInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InvitedByInverseTable = "users"
	// InvitedByColumn is the table column denoting the invited_by relation/edge.
	InvitedByColumn = "invited_by_id"
)

// Columns holds all SQL columns for invite fields.
var Columns = []string{
	FieldID,
	FieldToken,
	FieldEmail,
	FieldOrganizationID,
	FieldProjectID,
	FieldRole,
	FieldProjectPermission,
	FieldInvitedByID,
	FieldExpiresAt,
	FieldUsedAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Role defines the type for the "role" enum field.
type Role string

// RoleMember is the default value of the Role enum.
const DefaultRole = RoleMember

// Role values.
const (
	RoleOwner  Role = "owner"
	RoleAdmin  Role = "admin"
	RoleMember Role = "member"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleOwner, RoleAdmin, RoleMember:
		return nil
	default:
		return fmt.Errorf("invite: invalid enum value for role field: %q", r)
	}
}

// ProjectPermission defines the type for the "project_permission" enum field.
type ProjectPermission string

// ProjectPermissionView is the default value of the ProjectPermission enum.
const DefaultProjectPermission = ProjectPermissionView

// ProjectPermission values.
const (
	ProjectPermissionEdit ProjectPermission = "edit"
	ProjectPermissionView ProjectPermission = "view"
)

func (pp ProjectPermission) String() string {
	return string(pp)
}

// ProjectPermissionValidator is a validator for the "project_permission" field enum values. It is called by the builders before save.
func ProjectPermissionValidator(pp ProjectPermission) error {
	switch pp {
	case ProjectPermissionEdit, ProjectPermissionView:
		return nil
	default:
		return fmt.Errorf("invite: invalid enum value for project_permission field: %q", pp)
	}
}

// OrderOption defines the ordering options for the Invite queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByProjectID orders the results by the project_id field.
func ByProjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectID, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByProjectPermission orders the results by the project_permission field.
func ByProjectPermission(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectPermission, opts...).ToFunc()
}

// ByInvitedByID orders the results by the invited_by_id field.
func ByInvitedByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInvitedByID, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}

// ByProjectField orders the results by project field.
func ByProjectField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectStep(), sql.OrderByField(field, opts...))
	}
}

// ByInvitedByField orders the results by invited_by field.
func ByInvitedByField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInvitedByStep(), sql.OrderByField(field, opts...))
	}
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
func newProjectStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
	)
}
func newInvitedByStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InvitedByInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InvitedByTable, InvitedByColumn),
	)
}
